### ISSUE TITLE
Links broken?

### ISSUE THREAD

**Issue by HeatherWelch** [HeatherWelch/OPC_Farallons_end_products#2]
@FlukeAndFeather One issue I noticed is that the readme links seem to be broken. Perhaps I need to paste back in the directory path in at this line "mutate(file_path = raster_paths) "?

Also I'm not sure if I'm using issues right!

**Comment by FlukeAndFeather** [comment]
Fixed in pull request

**Comment by FlukeAndFeather** [comment]
Is the operationalization repo private? If so, can you add me as a collaborator? Or if not, send me a link?

**Comment by HeatherWelch** [comment]
Thanks Max, I've added you as a collaborator. Links look great thanks!

I tried to add the ramp indicators into the qmd. It renders find locally, and I've pushed both the qmd and md to github but I don't see the changes appearing. Any suggestions? I had to butcher your functions to make it work, sorry in advance

**Comment by FlukeAndFeather** [comment]
It's apparently a [known issue](https://github.com/orgs/community/discussions/23920)  on GitHub! Wild. If you open two-week metadata > 2023 > 07 you'll see it's actually truncated early.

I think the solution here is to move to a GitHub pages workflow. Here's [the lesson](https://flukeandfeather.github.io/BIOE215fall23/lessons/01_comp_proj_org.html#step-4-activate-github-pages) from my data science seminar on how to do that. I'd be happy to walk you through it the first time.

**Comment by HeatherWelch** [comment]
Thanks @FlukeAndFeather! I mainly got it working: https://heatherwelch.github.io/OPC_Farallons_end_products/

I'm still having an issue with hyperlinks to the products though. I changed my deploy branch from /docs to /main and was able to get one hyperlink working ("test" at the top of the page) so I know it's able to access the products. But the nested hyperlinks under year/month just appear as text instead of links. Any suggestions?

**Comment by HeatherWelch** [comment]
@FlukeAndFeather I made some progress but hit a new issue.

The progress what that  markdown="block" needs to be embedded in the upper level <details> before each year/month: https://github.com/just-the-docs/just-the-docs/issues/246

I've been able to do that manually in "index_this_works!.md" and successfully launch this github page: https://heatherwelch.github.io/OPC_Farallons_end_products/

I've edited your functions in index.qmd to paste markdown="block" in each upper level <details>. The functions work when I run each chunk in rstudio, but when I render the whole document "index.md" the markdown="block" text disappears and then github pages fails to process the links correctly. Would you be able to edit your functions to make this change? It's possible I just don't understand your syntax well enought
